name: Allegro Autoresponder

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalacja bibliotek
        run: pip install requests

      - name: Uruchomienie bota
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python main.py
